language: minimal
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install: brew install gcc
 # - os: windows
 #   install:
 #   - cd build
 #   - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
 #   - cmake --build . --target install

install:
- cd build
- cmake ..
- cmake --build . --parallel --target install

script: ctest --output-on-failure
