language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - ninja-build

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install:
#    - brew install gcc
#    - pip3 install meson


before_install: pip install meson

install:
- meson setup build
- meson install -C build

script: meson test -C build
